### ISSUE TITLE
What do you think to add option to `tap-gitlab` to disable extract Job ressources?

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-gitlab#41]
In GitLab by @stephane-klein on Sep 30, 2020, 10:01

What do you think to add option to `tap-gitlab` to disable extract Job ressources?

**Comment by pnadolny13** [comment]
In GitLab by @DouweM on Apr 26, 2021, 11:28

@stephane-klein Correct, `selected: true` needs to be set explicitly on any streams you'd like to import. If you're using Meltano, it can handle the catalog generation and stream selection for you automatically: https://meltano.com/docs/integration.html#selecting-entities-and-attributes-for-extraction

**Comment by Its-Alex** [comment]
For information purpose, `selected: true` must be put into `metadata`, in the object where `breadcrumb` is an empty array
