### ISSUE TITLE
Enumerate all Projects under a Group by using non-deprecated API

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-gitlab#56]
In GitLab by @aaronsteers on Aug 9, 2021, 12:30

As described in: https://gitlab.com/meltano/tap-gitlab/-/merge_requests/39

**Comment by pnadolny13** [comment]
In GitLab by @tayloramurphy on Sep 13, 2021, 11:30

assigned to @tayloramurphy

**Comment by ninomllr** [comment]
Just for those that need a workaround until this is possible, I creaded this bash command for it:
`curl -s "https://gitlab_instance/api/v4/groups?private_token=$TAP_GITLAB_PRIVATE_TOKEN&per_page=100" | jq -r '.[] | .full_path' | tr '\r\n' ' '`

**Comment by pnadolny13** [comment]
@ninomllr this was actually resolved in the gitlab repo prior to mirroring to github. I opened a PR with commits that didnt get migrated https://github.com/MeltanoLabs/tap-gitlab/pull/62

**Comment by pnadolny13** [comment]
I merged those commits so I'm going to close this issue!
